		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<title>@yield('title','')</title>
		<link rel="icon" type="image/vnd.microsoft.icon" href="favicon.ico" />
        <link rel="stylesheet" href="/autophp/css/global.css" type="text/css" />
        <link rel="stylesheet" href="/autophp/css/style.css" type="text/css" />
		<script src="/autophp/js/My97DatePicker/WdatePicker.js" type="text/javascript" language="javascript"></script>
		<script src="/autophp/js/common.js" type="text/javascript" language="javascript"></script>
		<script src="/autophp/js/jquery.js" type="text/javascript" language="javascript"></script>

